"""initial schema

Revision ID: ea2cb2e339b1
Revises: 
Create Date: 2026-10-07 23:44:56.964025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2cb2e339b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.Enum('positive', 'neutral', 'negative', name='effect', native_enum=False, create_constraint=False, length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("effect IN ('positive', 'neutral', 'negative')", name=op.f('ck_actions_effect')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions')),
    sa.UniqueConstraint('name', name=op.f('uq_actions_name'))
    )
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('satisfaction', sa.Enum('good', 'neutral', 'bad', name='satisfaction', native_enum=False, create_constraint=False, length=16), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("satisfaction IN ('good', 'neutral', 'bad')", name=op.f('ck_days_satisfaction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_days')),
    sa.UniqueConstraint('date', name=op.f('uq_days_date'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.Enum('positive', 'neutral', 'negative', name='effect', native_enum=False, create_constraint=False, length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("effect IN ('positive', 'neutral', 'negative')", name=op.f('ck_events_effect')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('name', name=op.f('uq_events_name'))
    )
    op.create_table('period_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('week', 'month', name='report_kind', native_enum=False, create_constraint=False, length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('week', 'month')", name=op.f('ck_period_reports_report_kind')),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_period_reports_period_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_period_reports')),
    sa.UniqueConstraint('kind', 'period_start', name='uq_period_reports_kind_period_start')
    )
    op.create_table('day_actions',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_day_actions_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], name=op.f('fk_day_actions_day_id_days'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day_id', 'action_id', name=op.f('pk_day_actions'))
    )
    op.create_table('day_events',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], name=op.f('fk_day_events_day_id_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_day_events_event_id_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('day_id', 'event_id', name=op.f('pk_day_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_events')
    op.drop_table('day_actions')
    op.drop_table('period_reports')
    op.drop_table('events')
    op.drop_table('days')
    op.drop_table('actions')
    # ### end Alembic commands ###
